import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'

const Ornaments = localFont({
  src: [
    {
      path: './fonts/BodoniOrnaments.ttf',
      weight: '400',
      style: 'normal',
    }
  ]
})

const LoveFromBold = localFont({
  src: [
    {
      path: './fonts/LoveFromBold.otf',
      style: 'normal',
    }
  ]
})

const Blackbike = localFont({
  src: [
    {
      path: './fonts/Blackbike-Clean.otf',
      style: 'normal',
    }
  ]
})

const CordierScript = localFont({
  src: [
    {
      path: './fonts/Cordier-Linked-Regular.ttf',
      style: 'normal',
    }
  ]
})

const Respira = localFont({
  src: [
    {
      path: './fonts/Respira-Black.ttf',
      style: 'normal',
    }
  ]
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
